{
 "title": "Arbitrum",
 "time": { "from": "now-15d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ETH USD TVL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_ethUsdTVL", "legendFormat": "Gas" }
   ]
  },
  {
   "title": "USD Fees",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_gasPrices_usd", "legendFormat": "{{action}} fee" }
   ]
  },
  {
   "title": "ArbGas Fees",
   "type": "stat",
   "gridPos": { "h": 22, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_gasPrices_arbGas", "legendFormat": "{{action}} ArbGas" }
   ]
  },
  {
   "title": "Gas Consumed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_gas", "legendFormat": "Gas" }
   ]
  },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "arbitrum_blocks", "legendFormat": "Blocks" },
    { "expr": "arbitrum_accounts", "legendFormat": "Accounts" },
    { "expr": "arbitrum_storage", "legendFormat": "Storage Slots" },
    { "expr": "arbitrum_transactions", "legendFormat": "Transactions" },
    { "expr": "arbitrum_contracts", "legendFormat": "Contracts" },
    { "expr": "arbitrum_gas", "legendFormat": "ArbGas" },
    { "expr": "arbitrum_gasPrices_usd", "legendFormat": "{{action}} $ price" },
    { "expr": "arbitrum_ethUsdTVL", "legendFormat": "ETH USD TVL" }
   ]
  },
  {
   "title": "Total Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_blocks", "legendFormat": "Blocks" }
   ]
  },
  {
   "title": "Total Contracts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_contracts", "legendFormat": "Contracts" }
   ]
  },
  {
   "title": "Total Accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_accounts", "legendFormat": "Accounts" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_transactions", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "Storage Slots Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_storage", "legendFormat": "Storage Slots" }
   ]
  },
  {
   "title": "ArbGas/sec Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_gasSpeedLimit" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 19 },
   "options": {
    "content": "# Made by [@transmissions11](https://twitter.com/transmissions11)\nFollow me on Twitter for L2 alpha or you're ngmi."
   },
   "targets": [
    { "expr": "arbitrum_gasPrices_arbGas", "legendFormat": "{{action}} ArbGas" }
   ]
  },
  {
   "title": "ArbGas/tx Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitrum_maxTxGasLimit" }
   ]
  }
 ]
}