{
 "title": "Fuse Asset Details",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "Asset",
    "query": {
     "query": "label_values(fuse_pool_assets_supply_usd{id=~\"$id\"}, symbol)"
    }
   },
   {
    "name": "id",
    "label": "Pool",
    "query": {
     "query": "label_values(fuse_pool_rss, id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Asset Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_borrow_usd{symbol=\"$symbol\", id=~\"$id\"}) / sum(fuse_pool_assets_supply_usd{symbol=\"$symbol\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "Amount Total Value Locked/Borrowed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_supply_amount{symbol=\"$symbol\", id=~\"$id\"})",
     "legendFormat": "TVL"
    },
    {
     "expr": "sum(fuse_pool_assets_borrow_amount{symbol=\"$symbol\", id=~\"$id\"})",
     "legendFormat": "TVB"
    }
   ]
  },
  {
   "title": "Amount TVL/TVB Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fuse_pool_assets_supply_amount{symbol=\"$symbol\", id=~\"$id\"}",
     "legendFormat": "Pool #{{id}} TVL"
    },
    {
     "expr": "fuse_pool_assets_borrow_amount{symbol=\"$symbol\", id=~\"$id\"}",
     "legendFormat": "Pool #{{id}} TVB"
    }
   ]
  },
  {
   "title": "Asset USD Total Supplied",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_supply_usd{symbol=\"$symbol\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "Asset USD Total Borrowed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_borrow_usd{symbol=\"$symbol\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "Events Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (event) (fuse_pool_assets_events{symbol=\"$symbol\", id=~\"$id\"})",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Interest Rates Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fuse_pool_assets_interest_rate{symbol=\"$symbol\", id=~\"$id\"}",
     "legendFormat": "Pool #{{id}} {{side}}"
    }
   ]
  },
  {
   "title": "USD TVL Per Pool",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_pool_assets_supply_usd{symbol=\"$symbol\"}",
     "legendFormat": "Pool #{{id}}"
    }
   ]
  },
  {
   "title": "USD TVB Per Pool",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_pool_assets_borrow_usd{symbol=\"$symbol\"}",
     "legendFormat": "Pool #{{id}}"
    }
   ]
  },
  {
   "title": "Fees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_fees_usd{symbol=\"$symbol\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "Reserves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_reserves_usd{symbol=\"$symbol\", id=~\"$id\"})"
    }
   ]
  },
  {
   "title": "Liquidations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_events{symbol=\"$symbol\", event=\"LiquidateBorrow\", id=~\"$id\"})"
    }
   ]
  }
 ]
}