{
 "title": "Erigon",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "quantile", "query": "0.5, 0.9, 0.97, 0.99, 1" },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(db_commit_seconds_count{phase=\"total\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_commit_seconds{phase=\"total\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_total: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_gc: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"write\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_write: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"sync\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_sync: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    }
   ]
  },
  {
   "title": "GC and State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "db_gc_leaf{instance=~\"$instance\"}",
     "legendFormat": "gc_leaf: {{instance}}"
    },
    {
     "expr": "db_gc_overflow{instance=~\"$instance\"}",
     "legendFormat": "gc_overflow: {{instance}}"
    },
    {
     "expr": "db_state_leaf{instance=~\"$instance\"}",
     "legendFormat": "state_leaf: {{instance}}"
    },
    {
     "expr": "db_state_branch{instance=~\"$instance\"}",
     "legendFormat": "state_branch: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Pages Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(db_pgops_clone{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "clone: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_split{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "split: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_spill{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "spill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_wops{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "wops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_unspill{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "unspill: {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tx_limit{instance=~\"$instance\"}",
     "legendFormat": "limit: {{instance}}"
    },
    {
     "expr": "tx_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "mem: resident set size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident mem: {{instance}}"
    },
    {
     "expr": "mem_data{instance=~\"$instance\"}",
     "legendFormat": "data: {{instance}}"
    },
    {
     "expr": "mem_stack{instance=~\"$instance\"}",
     "legendFormat": "stack: {{instance}}"
    },
    {
     "expr": "mem_locked{instance=~\"$instance\"}",
     "legendFormat": "locked: {{instance}}"
    },
    {
     "expr": "mem_swap{instance=~\"$instance\"}",
     "legendFormat": "swap: {{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write syscall/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_io_write_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "in: {{instance}}"
    },
    {
     "expr": "rate(process_io_read_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "out: {{instance}}"
    }
   ]
  },
  {
   "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(process_minor_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "soft: {{instance}}"
    },
    {
     "expr": "rate(process_major_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "hard: {{instance}}"
    }
   ]
  },
  {
   "title": "Process Mem: allocate objects/sec, free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "go_memstats_mallocs_total"
    },
    {
     "expr": "rate(go_memstats_frees_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "go_memstats_frees_total"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "go_cgo_calls_count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_cgo_calls_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "go_cgo_calls_count: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_system_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "increase(process_cpu_seconds_user_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "iowait: {{instance}}"
    }
   ]
  },
  {
   "title": "go memstat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_sys_bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  {
   "title": "GC Stop the World per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{quantile=\"0.75\",instance=~\"$instance\"}[$rate_interval])"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stage_headers{instance=~\"$instance\"}",
     "legendFormat": "Header: {{instance}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stage_headers{instance=~\"$instance\"}",
     "legendFormat": "blocks:{{instance}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid: {{instance}}"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid: {{instance}}"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "local: {{instance}}"
    }
   ]
  },
  { "title": "Private api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "gRPC call, error rates ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_started_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}, {{instance}}"
    },
    {
     "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}[1m])) ",
     "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}, {{instance}}"
    }
   ]
  }
 ]
}