{
 "title": "Fuse Fees/Reserves",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Pool ID",
    "query": {
     "query": "label_values(fuse_pool_rss, id)"
    }
   },
   {
    "name": "symbol",
    "label": "Asset",
    "query": {
     "query": "label_values(fuse_pool_assets_supply_amount{id=~\"$id\"}, symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unused Reserves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_reserves_usd{id=~\"$id\", symbol=~\"$symbol\"})"
    }
   ]
  },
  {
   "title": "Unclaimed Fuse Fees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_fees_usd{id=~\"$id\", symbol=~\"$symbol\"})"
    }
   ]
  },
  {
   "title": "Estimated Monthly Fuse Fees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(fuse_pool_assets_fees_usd{id=~\"$id\", symbol=~\"$symbol\"}[7d])) * 4"
    }
   ]
  },
  {
   "title": "Staked ALCX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fuse_staked_alcx_usd" }
   ]
  },
  {
   "title": "Earned ALCX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fuse_staked_alcx_unclaimed_usd" }
   ]
  },
  {
   "title": "Estimated Monthly Staking Profit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(fuse_staked_alcx_unclaimed_usd[14d]) * 2"
    }
   ]
  },
  {
   "title": "Reserves USD",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (symbol) (fuse_pool_assets_reserves_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Fuse Fees USD",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (symbol) (fuse_pool_assets_fees_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Fees/Reserves Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "fuse_staked_alcx_usd + fuse_staked_alcx_unclaimed_usd",
     "legendFormat": "Staked ALCX"
    },
    {
     "expr": "sum by (id) (fuse_pool_assets_fees_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "Pool #{{id}} Fees"
    },
    {
     "expr": "sum by (id) (fuse_pool_assets_reserves_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "Pool #{{id}} Reserves"
    }
   ]
  },
  {
   "title": "Reserves Per Asset",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (symbol) (fuse_pool_assets_reserves_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Reserves Per Pool",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id) (fuse_pool_assets_reserves_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "Pool #{{id}}"
    }
   ]
  },
  {
   "title": "Fuse Fees Per Asset",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (symbol) (fuse_pool_assets_fees_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Fuse Fees Per Pool",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id) (fuse_pool_assets_fees_usd{id=~\"$id\", symbol=~\"$symbol\"})",
     "legendFormat": "Pool #{{id}}"
    }
   ]
  }
 ]
}