{
 "title": "Fuse Overview",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "20s",
 "panels": [
  {
   "title": "Overall Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_borrow_usd) / sum(fuse_pool_assets_supply_usd)"
    }
   ]
  },
  {
   "title": "USD Total TVL/TVB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_supply_usd)",
     "legendFormat": "TVL"
    },
    {
     "expr": "sum(fuse_pool_assets_borrow_usd)",
     "legendFormat": "TVB"
    }
   ]
  },
  {
   "title": "Asset USD TVB/TVL ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (symbol) (fuse_pool_assets_supply_usd)",
     "legendFormat": "{{symbol}} TVL"
    },
    {
     "expr": "sum by (symbol) (fuse_pool_assets_borrow_usd)",
     "legendFormat": "{{symbol}} TVB"
    }
   ]
  },
  {
   "title": "USD Total Supplied",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_supply_usd)"
    }
   ]
  },
  {
   "title": "Liquidations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_events{event=\"LiquidateBorrow\"})"
    }
   ]
  },
  {
   "title": "User Leverage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(fuse_userLeverage{level=\"at_risk\"})",
     "legendFormat": "At Risk"
    },
    {
     "expr": "sum(fuse_userLeverage{level=\"liquidatable\"})",
     "legendFormat": "Liquidatable"
    }
   ]
  },
  {
   "title": "USD Total Borrowed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_borrow_usd)"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (event) (fuse_pool_assets_events)",
     "legendFormat": "{{symbol}} {{event}}"
    }
   ]
  },
  {
   "title": "Fees",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(fuse_pool_assets_fees_usd)" }
   ]
  },
  {
   "title": "Pool USD TVL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id) (fuse_pool_assets_supply_usd)",
     "legendFormat": "Pool #{{id}}"
    }
   ]
  },
  {
   "title": "Asset USD TVL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (symbol) (fuse_pool_assets_supply_usd)",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Asset USD TVB",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (symbol) (fuse_pool_assets_borrow_usd)",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "USD TVB/TVL Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (id) (fuse_pool_assets_supply_usd)",
     "legendFormat": "Pool #{{id}} TVL"
    },
    {
     "expr": "sum by (id) (fuse_pool_assets_borrow_usd)",
     "legendFormat": "Pool #{{id}} TVB"
    }
   ]
  }
 ]
}