{
 "title": "TurboGeth",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "chain_execution_number" }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "txpool_pending", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "db_size", "legendFormat": "Size" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_cpu_sysload", "legendFormat": "System" },
    { "expr": "system_cpu_syswait", "legendFormat": "Syswait" }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "targets": [
    { "expr": "chain_execution_number", "legendFormat": "Block Number" }
   ]
  },
  {
   "title": "Blocks Execution rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(chain_execution_number[1m])",
     "legendFormat": "Execution Rate"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "txpool_pending", "legendFormat": "Executable" },
    { "expr": "txpool_queued", "legendFormat": "Gapped" }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_rss", "legendFormat": "RSS" }
   ]
  },
  {
   "title": "gRPC call, error rates ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method) (rate(grpc_server_started_total[1m]))",
     "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}"
    },
    {
     "expr": "sum by (grpc_service, grpc_method) (rate(grpc_server_handled_total{grpc_code!=\"OK\"}[1m])) ",
     "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(system_disk_writebytes[1m])",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}